- name: Install bash-completion
  ansible.builtin.package:
    name: bash-completion
    state: present

- name: Enable bash-completion system-wide (Debian)
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    marker: "# {mark} ANSIBLE MANAGED - bash-completion"
    block: |
      if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
      fi
