- name: Install bash-completion
  ansible.builtin.apt:
    name: bash-completion
    state: present

- name: Enable bash-completion system-wide
  ansible.builtin.blockinfile:
    path: /etc/bash.bashrc
    marker: "# {mark} ANSIBLE MANAGED - bash-completion"
    block: |
      if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
      fi
