---
- name: Install dnf-automatic
  ansible.builtin.dnf:
    name:
      - dnf-automatic
    state: present

- name: Deploy dnf-automatic config
  ansible.builtin.template:
    src: templates/dnf/automatic.conf
    dest: /etc/dnf/automatic.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd

- name: Enable and start dnf-automatic timer
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
    state: started
