---

- name: Ensure firewalld is installed
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Ensure firewalld is enabled and started
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Open SSH port in firewalld
  ansible.posix.firewalld:
    service: ssh
    state: enabled
    permanent: true
    immediate: true
