# Setup sshd
- name: Configure sshd
  tags: ssh
  ansible.builtin.template:
    src: templates/ssh/00-sshd.conf
    dest: /etc/ssh/sshd_config.d/00-sshd.conf
    owner: root
    group: root
    mode: "0600"
    validate: sshd -t -f %s
  notify: Restart sshd
