# Setup admin user

# idempotency failure
- name: Create admin user
  ansible.builtin.user:
    name: "{{ admin_user }}"
    password: "{{ admin_password | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: true
    create_home: true
    state: present

- name: Add SSH public key for admin user
  ansible.posix.authorized_key:
    user: "{{ admin_user }}"
    key: "{{ admin_public_key }}"
    state: present
